services:
  frontend:
    image: ademahmudf/todo-app:cicd
    container_name: todo-app
    ports:
     - "80:3000"
    environment:
     - MYSQL_HOST=mysql
     - MYSQL_USER=root
     - MYSQL_PASSWORD=Password1
     - MYSQL_DB=todos
    networks:
     - todo_app
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
     - type: volume
       source: db-data
       target: /var/lib/mysql
       volume:
         nocopy: true
    environment:
     - MYSQL_ROOT_PASSWORD=Password1
     - MYSQL_DATABASE=todos
    networks:
     - todo_app

networks:
 todo_app:

volumes:
  db-data: